name: Deployement 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - name: installation des dependances
      run: echo 'Affiche du projet'

